---
label: Project
hide_body: false
display_field: title
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: tag_list
  name: categories
  label: Categories
- name: source_platform
  type: select
  default: []
  config:
    required: true
    options:
    - PrusaPrinters
    - Thingiverse
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Source Platform
- name: source_link
  type: text
  config:
    required: true
  label: Source Link
- name: download_link
  type: text
  config:
    required: false
  label: Download link
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- name: author
  type: text
  config:
    required: true
  label: Author
- name: author_link
  type: text
  config:
    required: false
  label: Author Link
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
  hidden: true
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
  hidden: true
pages:
- projects/Bathroom/soap-holder.md
- projects/Lamps/foliage-14-40.md
- projects/Lamps/gyroid-lampshade-1.md
- projects/Lamps/hangable-lamp-shade.md
- projects/Lamps/hex-table-lamp.md
- projects/Lamps/icosahedron-lamp-voronoi-pattern.md
- projects/Lamps/lamp-grow.md
- projects/Lamps/lampshade-1.md
- projects/Lamps/night-desk-lamp-peace-relax.md
- projects/Lamps/temple-of-venus-desktop-and-pendant-lamp.md
- projects/Organisation/ultimate-drawer-system.md
- projects/Tools/x6-tweezers.md
