---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: tag_list
  name: categories
  label: Categories
- name: download_link
  type: text
  config:
    required: false
  label: Download link
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
- name: source_link
  type: text
  config:
    required: true
  label: Source Link
- name: source_platform
  type: select
  default: []
  config:
    required: true
    options:
    - PrusaPrinters
    - Thingiverse
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Source Platform
pages:
- projects/3d-graff.md
- projects/cellular-lamp.md
- projects/chelsea-landmark.md
- projects/corner-clamps.md
- projects/designer-lithophane-moon-lamp.md
- projects/ios-concept.md
- projects/liquid-cuprum.print-in-place-lampshade.md
- projects/modular-tool-rail-system.md
- projects/orbital.structural-printing.print-in-place-lamp.md
- projects/sunk.md
- projects/table-clamp.md
