---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: tag_list
  name: categories
  label: Categories
- name: source_platform
  type: select
  default: []
  config:
    required: true
    options:
    - PrusaPrinters
    - Thingiverse
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Source Platform
- name: source_link
  type: text
  config:
    required: true
  label: Source Link
- name: download_link
  type: text
  config:
    required: false
  label: Download link
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- name: author
  type: text
  config:
    required: true
  label: Author
- name: author_link
  type: text
  config:
    required: false
  label: Author Link
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
  hidden: true
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
  hidden: true
pages:
- projects/24-7-lampshade.md
- projects/cellular-lamp.md
- projects/corner-clamps.md
- projects/designer-lithophane-moon-lamp.md
- projects/flower-lampshade-with-posable-petals-easy-to-print-assemble.md
- projects/gyroid-lampshade.md
- projects/happy-cloud-lamps-with-casting-shadow-effect.md
- projects/liquid-cuprum.print-in-place-lampshade.md
- projects/modular-moire-refracting-vase-lampshade-v1.3.md
- projects/modular-tool-rail-system.md
- projects/orbital.structural-printing.print-in-place-lamp.md
- projects/parametric-lamp.md
- projects/pentagon-lamp-shades.md
- projects/table-clamp.md
- projects/voronoi-lampshade-e27.md
- projects/voronoi-lampshade.md
